# Generated by Django 5.0.1 on 2024-11-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='quiz',
        ),
    ]
